// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjdY57CZDzjlquefUpXRGBe8yBSvGveSY',
    appId: '1:582174565948:web:74bfc031dcb8cf88b6c539',
    messagingSenderId: '582174565948',
    projectId: 'fir-connection-4a307',
    authDomain: 'fir-connection-4a307.firebaseapp.com',
    storageBucket: 'fir-connection-4a307.firebasestorage.app',
    measurementId: 'G-485RMW1YRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEXy9lt1TqN0Wrw6ReMvDxVWe6H4bYn4Y',
    appId: '1:582174565948:android:79ab69af93651401b6c539',
    messagingSenderId: '582174565948',
    projectId: 'fir-connection-4a307',
    storageBucket: 'fir-connection-4a307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcPTZgkKanEv5jzDag5AT7HGfmcYeL3HU',
    appId: '1:582174565948:ios:0ab981b0c1f0a786b6c539',
    messagingSenderId: '582174565948',
    projectId: 'fir-connection-4a307',
    storageBucket: 'fir-connection-4a307.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcPTZgkKanEv5jzDag5AT7HGfmcYeL3HU',
    appId: '1:582174565948:ios:0ab981b0c1f0a786b6c539',
    messagingSenderId: '582174565948',
    projectId: 'fir-connection-4a307',
    storageBucket: 'fir-connection-4a307.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjdY57CZDzjlquefUpXRGBe8yBSvGveSY',
    appId: '1:582174565948:web:bf8dbe1f8f7d2443b6c539',
    messagingSenderId: '582174565948',
    projectId: 'fir-connection-4a307',
    authDomain: 'fir-connection-4a307.firebaseapp.com',
    storageBucket: 'fir-connection-4a307.appspot.com',
    measurementId: 'G-2859GCG1C8',
  );
}
